In [0]:
import torch

In [0]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [121]:
torch.randn(5)

tensor([ 0.1072,  0.6125,  0.3296, -0.8763, -1.6768])

In [122]:
torch.randn(1,5)

tensor([[-0.7247,  0.9634,  0.1342,  0.5485,  2.1349]])

In [123]:
torch.randn(1,1)

tensor([[-0.8782]])

In [124]:
torch.randn((1,5))

tensor([[-2.0826,  1.8317, -0.5535,  1.0395, -1.2601]])

In [125]:
torch.randn((2,5))

tensor([[ 0.4156, -1.3031,  0.4350, -1.1498, -0.8150],
        [-0.9118, -0.0739,  1.1056, -0.8667, -0.1373]])

In [0]:
torch.manual_seed(7)
features=torch.randn((1,5))
weights=torch.randn_like(features)
bias=torch.randn((1,1))

In [0]:
## Calculate the output of this network using the weights and bias tensors

In [128]:
torch.sum((features*weights)+bias)

tensor(-0.3912)

In [129]:
torch.mm(features,weights.view(5,1))+bias

tensor([[-1.6619]])

In [0]:
output=activation(torch.sum((features*weights)+bias))

In [131]:
output

tensor(0.4034)

In [0]:
## Calculate the output of this network using the weights and bias tensors using matrix multiplication

In [0]:
output=activation(torch.mm(features,weights.view(5,1))+bias)

In [134]:
output

tensor([[0.1595]])

In [0]:
## Calculate the output for multilayer neural network using the weights and bias tensors using matrix multiplication

In [136]:
features.shape[1]

5

In [137]:
torch.randn((1,n_output))

tensor([[0.1328]])

In [0]:
torch.manual_seed(7)
features=torch.randn((1,3))
n_input=(features.shape[1])
n_hidden=2
n_output=1
W1=torch.randn(n_input,n_hidden)
W2=torch.randn(n_hidden,n_output)
B1=torch.randn(1,n_hidden)
B2=torch.randn((1,n_output))

In [139]:
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [140]:
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [141]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [142]:
B2

tensor([[0.2405]])

In [143]:
B2

tensor([[0.2405]])

In [144]:
torch.mm(features,W1)

tensor([[ 0.6270, -0.3969]])

In [145]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [146]:
W2.view(1,2)

tensor([[-1.6822,  0.3177]])

In [147]:
output1=activation(torch.mm(features,W1)+B1)
output1

tensor([[0.6813, 0.4355]])

In [152]:
output2=activation(torch.mm(output1,W2)+B2)
output2

tensor([[0.3171]])

In [0]:
output2=activation(torch.mm(activation(torch.mm(features,W1)+B1),W2+B2))
output2

In [0]:
#Numpy to torch and back

In [0]:
import numpy as np

In [151]:
np.random.rand(5)

array([0.60084503, 0.88256178, 0.28224082, 0.83288371, 0.15871551])

In [0]:
a=np.random.rand(4,3)
a

array([[0.40328158, 0.87631944, 0.74406603],
       [0.14913328, 0.66824549, 0.12579496],
       [0.14972968, 0.18761243, 0.8927442 ],
       [0.19268025, 0.92723693, 0.40269879]])

In [0]:
b=torch.from_numpy(a)
b

tensor([[0.4033, 0.8763, 0.7441],
        [0.1491, 0.6682, 0.1258],
        [0.1497, 0.1876, 0.8927],
        [0.1927, 0.9272, 0.4027]], dtype=torch.float64)

In [0]:
b.numpy()

array([[0.40328158, 0.87631944, 0.74406603],
       [0.14913328, 0.66824549, 0.12579496],
       [0.14972968, 0.18761243, 0.8927442 ],
       [0.19268025, 0.92723693, 0.40269879]])

In [0]:
b.mul_(2)

tensor([[0.8066, 1.7526, 1.4881],
        [0.2983, 1.3365, 0.2516],
        [0.2995, 0.3752, 1.7855],
        [0.3854, 1.8545, 0.8054]], dtype=torch.float64)