In [0]:
import torch

In [0]:
def activation(x):
  return 1/1+torch.exp(-x)

In [40]:
torch.randn(5)

tensor([-0.9837, -1.2494, -0.1883,  0.2827,  0.1305])

In [90]:
torch.randn(1,5)

tensor([[1.3955, 1.3470, 2.4382, 0.2028, 2.4505]])

In [91]:
torch.randn(1,1)

tensor([[2.0256]])

In [0]:
torch.manual_seed(7)
features=torch.randn((1,5))
weights=torch.randn_like(features)
bias=torch.randn((1,1))

In [0]:
## Calculate the output of this network using the weights and bias tensors

In [49]:
torch.sum((features*weights)+bias)

tensor(-0.3912)

In [50]:
torch.mm(features,weights.view(5,1))+bias

tensor([[-1.6619]])

In [0]:
output=activation(torch.sum((features*weights)+bias))

In [46]:
output

tensor(2.4787)

In [0]:
## Calculate the output of this network using the weights and bias tensors using matrix multiplication

In [0]:
output=activation(torch.mm(features,weights.view(5,1))+bias)

In [48]:
output

tensor([[6.2693]])

In [0]:
## Calculate the output for multilayer neural network using the weights and bias tensors using matrix multiplication

In [0]:
torch.manual_seed(7)
features=torch.randn((1,3))
n_input=(features.shape[1])
n_hidden=2
n_output=1
W1=torch.randn(n_input,n_hidden)
W2=torch.randn(n_hidden,n_output)
B1=torch.randn(1,n_hidden)
B2=torch.randn((1,n_output))

In [97]:
features

tensor([[-0.1468,  0.7861,  0.9468]])

In [73]:
W1

tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])

In [74]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [75]:
B2

tensor([[0.2405]])

In [76]:
B2

tensor([[0.2405]])

In [79]:
torch.mm(features,W1)

tensor([[ 0.6270, -0.3969]])

In [93]:
W2

tensor([[-1.6822],
        [ 0.3177]])

In [92]:
W2.view(1,2)

tensor([[-1.6822,  0.3177]])

In [101]:
output1=activation(torch.mm(features,W1)+B1)
output1

tensor([[1.4678, 2.2964]])

In [86]:
output2=activation(torch.mm(output1,W2.view(1,2))+B2)
output2

tensor([[7.8903e+03, 1.1380e+00]])

In [96]:
output2=activation(torch.mm(activation(torch.mm(features,W1)+B1),W2+B2))
output2

tensor([[3.3027]])

In [0]:
#Numpy to torch and back

In [0]:
import numpy as np

In [107]:
np.random.rand(5)

array([0.5162078 , 0.22111755, 0.24397982, 0.1539098 , 0.43345886])

In [105]:
a=np.random.rand(4,3)
a

array([[0.40328158, 0.87631944, 0.74406603],
       [0.14913328, 0.66824549, 0.12579496],
       [0.14972968, 0.18761243, 0.8927442 ],
       [0.19268025, 0.92723693, 0.40269879]])

In [108]:
b=torch.from_numpy(a)
b

tensor([[0.4033, 0.8763, 0.7441],
        [0.1491, 0.6682, 0.1258],
        [0.1497, 0.1876, 0.8927],
        [0.1927, 0.9272, 0.4027]], dtype=torch.float64)

In [109]:
b.numpy()

array([[0.40328158, 0.87631944, 0.74406603],
       [0.14913328, 0.66824549, 0.12579496],
       [0.14972968, 0.18761243, 0.8927442 ],
       [0.19268025, 0.92723693, 0.40269879]])

In [110]:
b.mul_(2)

tensor([[0.8066, 1.7526, 1.4881],
        [0.2983, 1.3365, 0.2516],
        [0.2995, 0.3752, 1.7855],
        [0.3854, 1.8545, 0.8054]], dtype=torch.float64)